### ISSUE TITLE
Multiple Dashboards are created on every navigation from one tab to another

### ISSUE THREAD

**Issue by AMITSRIVASTAVAEC** [hawtio/hawtio-dashboard#4]
Multiple Dashboards are created on every navigation from one tab to another.
Moreover the sub-tabs panel also gets populated by sets of dashboards

**Comment by gashcrumb** [comment]
@AMITSRIVASTAVAEC should be all set, you can verify in a few minutes on http://dashboard.hawt.io, thanks for spotting that!

**Comment by AMITSRIVASTAVAEC** [comment]
@gashcrumb thank you :)
